config/routes.rb
Favoritos::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users do
    resources :links, only: [:create, :destroy, :edit, :update, :show]
  end

  resources :tags, only: [:show]

  root to: "homes#show", via: :get

end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_writer :tag_names

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	
	belongs_to :user
	URL_REGEX = /\A(http|https):\/\/|[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?\z/
	validates :url, presence: true, format: {with: URL_REGEX}

	has_attached_file :image, styles: {
		thumb: "200x200>"
	}, :default_url => "/assets/:style/loading.gif"

	default_scope -> {order("created_at DESC")}

	after_save :create_tags

	def tag_names
		@tag_names || tags.map(&:name).join(', ')
	end

	def register
		return false unless save
		# get_title_and_image
		create_job
		true
	end

	def update_and_reload(params)
		self.url = params[:url]
		self.page_title = params[:page_title]
		self.description = params[:description]
		self.tag_names = params[:tag_names]
		save
		# get_title_and_image
		create_job
	end

	def create_job
		Delayed::Job.enqueue(LinkJob.new(id), run_at: Time.now)
	end

	def get_title_and_image
		save_page_title(self.id)
		save_page_image(self.id)
	end

	private

	def create_tags
		if @tag_names
			self.tags = @tag_names.split(/,\s*/).map do |tag|
				Tag.find_or_create_by(name: tag)
			end
		end
	end

	def save_page_title(id)
		link = Link.find(id)
		return unless link.page_title.nil? or link.page_title.empty?
		link.page_title = get_page_title(link.url)
		link.save
	end

	def save_page_image(id)
		link = Link.find(id)
		file = create_temp_file(imgkit(link.url))
		link.image = file
		link.save
		file.unlink
		true
  end

  def get_page_title(url)
  	agent = Mechanize.new
		page = agent.get(url)
		page.title
  end

  def create_temp_file(img)
  	file = Tempfile.new(["template_#{id}", 'png'], 'tmp',
		                     :encoding => 'ascii-8bit')
		file.write(img)
		file.flush
		file
  end

  def imgkit(url)
  	kit = IMGKit.new(url)
		kit.to_img(:png)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :links, through: :taggings

	validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :link
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :links, dependent: :destroy
	
	has_secure_password
	validates :username, presence: true, length: {minimum: 4}
	validates :email, 
						presence: true,
						format: {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}

	after_create :send_user_mailer

	def send_user_mailer
		Delayed::Job.enqueue(MailerJob.new(id), run_at: Time.now)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out
  	session[:user_id] = nil
  end


  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def show
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  respond_to :html, :json

  def show
    @link = Link.find(params[:id])
    respond_with @link
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(url: params[:link][:url])
    if @link.register
      redirect_to root_path, notice: 'Link was successfully created.'
    else
      redirect_to root_path, notice: @link.errors.full_messages.join(" and ")
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_and_reload(link_params)
      redirect_to root_path, notice: "Link was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    link = current_user.links.find(params[:id])
    link.destroy
    redirect_to root_path, notice: 'Link deleted.'
  end

  private
  
  def link_params
    params.require(:link).permit(:url, :description, :page_title, :tag_names)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		sign_in user
  		redirect_to root_path, notice: "Logged in"
  	else
  		redirect_to new_session_path, notice: "Wrong username or password"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    sign_out
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user_can_edit(link)
		return true if current_user && current_user == link.user
		return false
	end

	def current_user_can_post_to_this_page(user)
		return current_user == user
	end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/show.html.erb
<% if current_user %>
	<%= render current_user %>
<% else %>
	<h2>Please Log in</h2>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Fav", root_path  %> | 
<% if current_user %>
	<%= link_to "Log out", session_path, method: :delete %>
<% else %>
	<%= link_to "Log in", new_session_path %> | 
	<%= link_to "Sign up", new_user_path %>
<% end %>
 | <%= link_to "Users", users_path %>

app/views/layouts/_notifications.html.erb
<% if notice %>
	<p>
		<%= notice %>
	</p>
<% end %>

<% if alert %>
	<p>
		<%= alert %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meus Favoritos</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<header>
		<%= render "layouts/header" %>
	</header>

	<div class="notifications">
		<%= render "layouts/notifications" %>
	</div>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for :link, url: user_links_path(current_user) do |form| %>
	<%= form.text_field :url, placeholder: "Url here", id: "new_link" %>
	<%= form.submit "Salvar" %>
<% end %>

app/views/links/_link.html.erb
<div class="link">
	<%= link_to( 
			image_tag(
						link.image.url(:thumb), 
						class: "thumb",
						data: {link_url: user_link_path(current_user, link)}), 
			link.url, 
			target: "_blank") %>
	Title: <span id="title_<%= link.id %>"><%= link.page_title %></span>
	<div class="tags">
		<ul>
			<%= render link.tags %>
		</ul>
	</div>
	<p>
	<% if current_user_can_edit(link) %>	
		<%= link_to("Delete", user_link_path(current_user, link), 
								method: :delete,
								data: {confirm: "Tem certeza que quer eliminar o link?"}) %> | 
		<%= link_to "Edit", edit_user_link_path(current_user, link) %>
	<% end %>
	</p>
</div>

app/views/links/_new.html.erb
<div class="new-link">
	<%= render "links/form" %>
</div>

app/views/links/edit.html.erb
<div class="edit-link">
	<%= form_for [current_user, @link] do |form| %>
		<div class="form-group">
			<%= form.text_field :url, placeholder: "Url here" %>
		</div>
		<div class="form-group">
			<%= form.text_field :page_title, placeholder: "Page title" %>
		</div>
		<div class="form-group">
			<%= form.text_field :tag_names, placeholder: "Tag names, separated by commas" %>
		</div>
		<div class="form-group">
			<%= form.text_area :description, placeholder: "Description" %>
		</div>
		<%= form.submit "Salvar" %>
	<% end %>
</div>

app/views/tags/_tag.html.erb
<li class="tag">
	<%= link_to "##{tag.name}", tag %>
</li>

app/views/tags/show.html.erb
<h1>Links tagged with: <%= @tag.name %></h1>
<div class="links">
	<%= render @tag.links %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="user">
	<h1>
		<%= user.name %>
	</h1>
	
	<% if current_user_can_post_to_this_page user %>
		<%= render "links/new" %>
	<% end %>

	<div class="link">
		<%= render user.links %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render @user %>
<%= link_to('Edit', edit_user_path(@user)) if current_user == @user %>